"""Generated by AxiomTestGen — TASK-03.2 (Fixed-window rate limiter).

Oracle source: spec.md §4 (AC-03.2.1 .. AC-03.2.6). Deterministic clock injected;
no wall-clock, network, or unseeded randomness. Each test names its case_id + AC.
"""
import pytest

from ratelimit.limiter import RateLimiter, Decision


class FakeClock:
    """Deterministic, controllable time source (SpecPod determinism rule)."""
    def __init__(self, t: float = 1000.0):
        self.t = t

    def __call__(self) -> float:
        return self.t

    def advance(self, dt: float) -> None:
        self.t += dt


@pytest.fixture
def clock() -> FakeClock:
    return FakeClock()


@pytest.fixture
def limiter(clock: FakeClock) -> RateLimiter:
    # limit=3 within a 60s window
    return RateLimiter(limit=3, window_seconds=60, clock=clock)


# --- AC-03.2.1 — requests at/under limit are allowed --------------------------

def test_tc_001_under_limit_allowed(limiter):
    """TC-03.2-001 · AC-03.2.1 · EP(valid). First request under limit is allowed."""
    d = limiter.check("client-a")
    assert d.allowed is True
    assert d.remaining == 2


def test_tc_002_at_limit_boundary_allowed(limiter):
    """TC-03.2-002 · AC-03.2.1 · BVA(on-boundary). Request AT the limit is allowed, remaining hits 0."""
    limiter.check("client-a")
    limiter.check("client-a")
    third = limiter.check("client-a")  # 3rd of limit=3
    assert third.allowed is True
    assert third.remaining == 0


@pytest.mark.parametrize(
    "request_index, expected_remaining",
    [(1, 2), (2, 1), (3, 0)],  # EP across the allowed range
)
def test_tc_009_remaining_decrements(limiter, request_index, expected_remaining):
    """TC-03.2-009 · AC-03.2.1 · EP(parametrized). remaining decrements per request."""
    d = None
    for _ in range(request_index):
        d = limiter.check("client-a")
    assert d.allowed is True
    assert d.remaining == expected_remaining


# --- AC-03.2.2 — exceeding the limit is throttled -----------------------------

def test_tc_003_over_limit_throttled(limiter):
    """TC-03.2-003 · AC-03.2.2 · BVA(just-above). limit+1 request is throttled."""
    for _ in range(3):
        limiter.check("client-a")
    fourth = limiter.check("client-a")
    assert fourth.allowed is False
    assert fourth.remaining == 0


def test_tc_004_throttle_sets_retry_after(limiter):
    """TC-03.2-004 · AC-03.2.2 · positive-oracle. retry_after is positive when throttled."""
    for _ in range(3):
        limiter.check("client-a")
    fourth = limiter.check("client-a")
    assert fourth.retry_after > 0
    assert fourth.retry_after <= 60


# --- AC-03.2.3 — invalid construction raises ----------------------------------

@pytest.mark.parametrize("bad_limit", [0, -1])
def test_tc_005_invalid_limit_raises(clock, bad_limit):
    """TC-03.2-005 · AC-03.2.3 · negative+boundary. limit < 1 raises ValueError."""
    with pytest.raises(ValueError):
        RateLimiter(limit=bad_limit, window_seconds=60, clock=clock)


@pytest.mark.parametrize("bad_window", [0, -5])
def test_tc_006_invalid_window_raises(clock, bad_window):
    """TC-03.2-006 · AC-03.2.3 · negative+boundary. window_seconds <= 0 raises ValueError."""
    with pytest.raises(ValueError):
        RateLimiter(limit=3, window_seconds=bad_window, clock=clock)


# --- AC-03.2.4 — window rollover resets the counter (state-transition) --------

def test_tc_008_window_rollover_resets(limiter, clock):
    """TC-03.2-008 · AC-03.2.4 · state-transition. After window elapses, requests allowed again."""
    for _ in range(3):
        limiter.check("client-a")
    assert limiter.check("client-a").allowed is False   # THROTTLED state
    clock.advance(60)                                    # window elapses
    rolled = limiter.check("client-a")                   # -> OPEN state
    assert rolled.allowed is True
    assert rolled.remaining == 2


# --- AC-03.2.6 — independent client keys --------------------------------------

def test_tc_007_distinct_keys_independent(limiter):
    """TC-03.2-007 · AC-03.2.6 · partition(by-key). One client's limit does not affect another."""
    for _ in range(3):
        limiter.check("client-a")
    assert limiter.check("client-a").allowed is False
    other = limiter.check("client-b")
    assert other.allowed is True
    assert other.remaining == 2

# NOTE: AC-03.2.5 (backward clock skew) is intentionally NOT tested — spec oracle
# is undefined. See coverage-gap-report.md (BLOCKING).
