#!/usr/bin/env python3
"""
drift-scorer.py
Generated by DriftGuard — SpecPod Operate Phase v2.1.0
Agent: O-02 DriftGuard

Samples production outputs, scores them against the spec baseline using
Claude Sonnet, and produces structured drift reports.

DO NOT EDIT MANUALLY — regenerate via DriftGuard skill.
"""

import json
import yaml
import logging
import datetime
import requests
from pathlib import Path
from typing import Optional

# ── Configuration ─────────────────────────────────────────────────────────────
DRIFT_CONFIG_FILE    = "operate/drift-guard/drift-config.yaml"
DRIFT_REPORT_FILE    = "operate/drift-guard/drift-report.md"
BASELINE_DIR         = "operate/drift-guard/eval-baseline/"
FEEDBACK_FILE        = "operate/feedback-loop-triggers.yaml"
REVALIDATION_FILE    = "operate/drift-guard/revalidation-trigger.yaml"
OPENSPEC_FILE        = "artifacts/openspec.yaml"
ANTHROPIC_API_URL    = "https://api.anthropic.com/v1/messages"
ANTHROPIC_API_KEY    = ""  # Set via environment: ANTHROPIC_API_KEY

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
log = logging.getLogger("drift-guard")

# ── Config Loader ─────────────────────────────────────────────────────────────
def load_config() -> dict:
    with open(DRIFT_CONFIG_FILE) as f:
        return yaml.safe_load(f)

def load_openspec() -> dict:
    with open(OPENSPEC_FILE) as f:
        return yaml.safe_load(f)

# ── Production Sampler ────────────────────────────────────────────────────────
def sample_production_outputs(config: dict) -> list:
    """
    Reads sampled production outputs.
    Actual implementation adapts to the observability stack.
    This sample reads from a local log file written by the sampling sidecar.
    """
    sample_log = Path("operate/drift-guard/sampled-outputs.jsonl")
    outputs = []
    if sample_log.exists():
        with open(sample_log) as f:
            for line in f:
                try:
                    outputs.append(json.loads(line.strip()))
                except json.JSONDecodeError:
                    pass
    log.info("Loaded %d sampled outputs for evaluation", len(outputs))
    return outputs

# ── Baseline Loader ───────────────────────────────────────────────────────────
def load_baseline(feature_id: str) -> Optional[list]:
    baseline_path = Path(BASELINE_DIR) / f"{feature_id}-golden.jsonl"
    if not baseline_path.exists():
        log.warning("No baseline found for feature: %s", feature_id)
        return None
    outputs = []
    with open(baseline_path) as f:
        for line in f:
            try:
                outputs.append(json.loads(line.strip()))
            except json.JSONDecodeError:
                pass
    return outputs

# ── Claude Scorer ─────────────────────────────────────────────────────────────
def score_output_with_claude(
    feature_id: str,
    production_output: str,
    golden_output: str,
    acceptance_criteria: str,
    dimension: str
) -> dict:
    """
    Uses Claude Sonnet to score semantic drift between production output and golden baseline.
    Returns: {score: float, reasoning: str, dimension: str}
    """
    scoring_prompt = f"""You are a strict AI output quality evaluator for the SpecPod framework.

FEATURE: {feature_id}
DIMENSION: {dimension}
ACCEPTANCE CRITERIA: {acceptance_criteria}

GOLDEN BASELINE OUTPUT:
{golden_output}

PRODUCTION OUTPUT (to evaluate):
{production_output}

Score the PRODUCTION OUTPUT on a scale of 0.0 to 1.0 where:
- 1.0 = Identical quality and behaviour to golden baseline, fully meets acceptance criteria
- 0.8 = Minor deviation, all criteria met, acceptable in production
- 0.6 = Moderate drift, some criteria not fully met, warrants monitoring
- 0.4 = Significant drift, multiple criteria failures, revalidation recommended
- 0.0 = Complete failure, output meaningless or harmful

Respond ONLY in this JSON format:
{{"score": 0.0, "reasoning": "one sentence", "dimension": "{dimension}", "regression": true/false}}"""

    import os
    api_key = os.environ.get("ANTHROPIC_API_KEY", ANTHROPIC_API_KEY)

    try:
        resp = requests.post(
            ANTHROPIC_API_URL,
            headers={"x-api-key": api_key, "Content-Type": "application/json",
                     "anthropic-version": "2023-06-01"},
            json={
                "model": "claude-sonnet-4-20250514",
                "max_tokens": 256,
                "messages": [{"role": "user", "content": scoring_prompt}]
            },
            timeout=30
        )
        resp.raise_for_status()
        content = resp.json()["content"][0]["text"]
        return json.loads(content)
    except Exception as e:
        log.error("Scoring API call failed: %s", e)
        return {"score": None, "reasoning": f"API error: {e}", "dimension": dimension, "regression": None}

# ── Drift Report Writer ───────────────────────────────────────────────────────
def write_drift_report(results: list, config: dict):
    report_path = Path(DRIFT_REPORT_FILE)
    report_path.parent.mkdir(parents=True, exist_ok=True)

    threshold = config.get("drift_threshold", 0.80)
    ts = datetime.datetime.utcnow().isoformat() + "Z"

    with open(report_path, "a") as f:
        f.write(f"\n## Drift Evaluation — {ts}\n\n")
        f.write(f"Threshold: {threshold} | Samples evaluated: {len(results)}\n\n")
        f.write("| Feature | Dimension | Score | Baseline | Delta | Direction | Severity |\n")
        f.write("|---|---|---|---|---|---|---|\n")
        for r in results:
            delta = round((r.get("score", 0) or 0) - r.get("baseline_score", 1.0), 4)
            direction = "regression" if delta < 0 else "improvement"
            score = r.get("score", "N/A")
            severity = "critical" if (score is not None and score < 0.60) else \
                       "warning" if (score is not None and score < threshold) else "info"
            f.write(
                f"| {r['feature_id']} | {r['dimension']} | {score} "
                f"| {r.get('baseline_score', 'N/A')} | {delta:+.4f} | {direction} | {severity} |\n"
            )

# ── Revalidation Trigger ──────────────────────────────────────────────────────
def write_revalidation_trigger(breaching_features: list, config: dict):
    trigger = {
        "triggered_at": datetime.datetime.utcnow().isoformat() + "Z",
        "trigger_source": "DriftGuard",
        "threshold": config.get("drift_threshold", 0.80),
        "breaching_features": breaching_features,
        "recommended_action": "Re-run EvalHarness against current production deployment",
        "notification_sent": config.get("revalidation_target", "log only")
    }
    with open(REVALIDATION_FILE, "w") as f:
        yaml.dump(trigger, f, default_flow_style=False)
    log.warning("Revalidation trigger written: %s", REVALIDATION_FILE)

# ── Feedback Loop ─────────────────────────────────────────────────────────────
def write_feedback_loop(results: list, config: dict):
    fb_path = Path(FEEDBACK_FILE)
    existing = {}
    if fb_path.exists():
        with open(fb_path) as f:
            existing = yaml.safe_load(f) or {}

    threshold = config.get("drift_threshold", 0.80)
    breaching = [r for r in results if r.get("score") is not None and r["score"] < threshold]
    overall = "critical" if any(r.get("score", 1) < 0.60 for r in breaching) else \
              "warning" if breaching else "info"

    existing["drift_guard"] = {
        "generated_at": datetime.datetime.utcnow().isoformat() + "Z",
        "summary": f"Drift evaluation: {len(results)} samples. {len(breaching)} feature(s) below threshold.",
        "triggers": [
            {
                "feature_id": r["feature_id"],
                "dimension": r["dimension"],
                "drift_score": r.get("score"),
                "delta": round((r.get("score", 1) or 1) - r.get("baseline_score", 1.0), 4),
                "direction": "regression" if (r.get("score", 1) or 1) < r.get("baseline_score", 1.0) else "improvement",
                "severity": "critical" if (r.get("score", 1) or 1) < 0.60 else "warning"
            }
            for r in breaching
        ],
        "severity": overall
    }

    with open(fb_path, "w") as f:
        yaml.dump(existing, f, default_flow_style=False, sort_keys=False)

# ── Main ──────────────────────────────────────────────────────────────────────
def main():
    config = load_config()
    openspec = load_openspec()
    threshold = config.get("drift_threshold", 0.80)

    log.info("DriftGuard evaluation starting. Threshold: %s", threshold)

    sampled = sample_production_outputs(config)
    if not sampled:
        log.warning("No sampled outputs available. Check sampling sidecar.")
        return

    results = []
    breaching_features = []

    for sample in sampled:
        feature_id = sample.get("feature_id")
        if not feature_id:
            continue

        golden_outputs = load_baseline(feature_id)
        golden_text = golden_outputs[0].get("output", "") if golden_outputs else ""

        acceptance_criteria = (
            openspec.get("features", {})
                    .get(feature_id, {})
                    .get("acceptance_criteria", "No specific criteria defined.")
        )

        for dimension in config.get("drift_dimensions", ["semantic"]):
            result = score_output_with_claude(
                feature_id=feature_id,
                production_output=sample.get("output", ""),
                golden_output=golden_text,
                acceptance_criteria=acceptance_criteria,
                dimension=dimension
            )
            result["feature_id"] = feature_id
            result["baseline_score"] = 1.0  # golden baseline is reference
            results.append(result)

            score = result.get("score")
            if score is not None and score < threshold:
                log.warning("DRIFT BREACH: %s / %s score=%.3f", feature_id, dimension, score)
                if feature_id not in breaching_features:
                    breaching_features.append(feature_id)

    write_drift_report(results, config)

    if breaching_features:
        write_revalidation_trigger(breaching_features, config)

    write_feedback_loop(results, config)
    log.info("DriftGuard evaluation complete. %d results. %d breaches.", len(results), len(breaching_features))

if __name__ == "__main__":
    main()
