#!/usr/bin/env python3
"""
runtime-iq-monitor.py
Generated by RuntimeIQ — SpecPod Operate Phase v2.1.0
Agent: O-01 RuntimeIQ

Continuously polls the observability stack, evaluates SLA thresholds,
triggers alerts, requests scaling, and writes to feedback-loop-triggers.yaml.

DO NOT EDIT MANUALLY — regenerate via RuntimeIQ skill.
"""

import json
import time
import yaml
import logging
import requests
import datetime
from pathlib import Path
from typing import Optional

# ── Configuration ────────────────────────────────────────────────────────────
THRESHOLDS_FILE   = "operate/runtime-iq/thresholds.yaml"
BREACH_LOG_FILE   = "operate/runtime-iq/sla-breach-log.md"
FEEDBACK_FILE     = "operate/feedback-loop-triggers.yaml"
METRICS_ENDPOINT  = "http://prometheus.monitoring.svc.cluster.local:9090"
ALERT_WEBHOOK     = "https://hooks.slack.com/services/PLACEHOLDER"
POLL_INTERVAL_S   = 60
LOG_LEVEL         = logging.INFO

logging.basicConfig(level=LOG_LEVEL, format="%(asctime)s [%(levelname)s] %(message)s")
log = logging.getLogger("runtime-iq")

# ── Threshold Loader ─────────────────────────────────────────────────────────
def load_thresholds() -> dict:
    with open(THRESHOLDS_FILE) as f:
        return yaml.safe_load(f)

# ── Prometheus Metric Fetcher ────────────────────────────────────────────────
def fetch_metric(query: str) -> Optional[float]:
    """Execute a PromQL instant query, return scalar value or None."""
    try:
        resp = requests.get(
            f"{METRICS_ENDPOINT}/api/v1/query",
            params={"query": query},
            timeout=10
        )
        resp.raise_for_status()
        data = resp.json()
        results = data.get("data", {}).get("result", [])
        if results:
            return float(results[0]["value"][1])
    except Exception as e:
        log.error(f"Metric fetch failed for query '{query}': {e}")
    return None

# ── SLA Evaluator ─────────────────────────────────────────────────────────────
def evaluate_sla(thresholds: dict) -> list:
    """
    Evaluate all features against their thresholds.
    Returns list of breach events.
    """
    breaches = []
    for feature, cfg in thresholds.get("features", {}).items():
        severity_map = cfg.get("alert_severity_map", {"warning": 0.80, "critical": 1.00})

        # p95 latency
        if "latency_p95_ms" in cfg:
            val = fetch_metric(
                f'histogram_quantile(0.95, rate(http_request_duration_ms_bucket{{feature="{feature}"}}[5m]))'
            )
            if val is not None:
                _check_threshold(breaches, feature, "latency_p95_ms", val,
                                 cfg["latency_p95_ms"], severity_map)

        # p99 latency
        if "latency_p99_ms" in cfg:
            val = fetch_metric(
                f'histogram_quantile(0.99, rate(http_request_duration_ms_bucket{{feature="{feature}"}}[5m]))'
            )
            if val is not None:
                _check_threshold(breaches, feature, "latency_p99_ms", val,
                                 cfg["latency_p99_ms"], severity_map)

        # error rate 5xx
        if "error_rate_5xx_pct" in cfg:
            val = fetch_metric(
                f'rate(http_requests_total{{feature="{feature}",status=~"5.."}}[5m]) * 100'
            )
            if val is not None:
                _check_threshold(breaches, feature, "error_rate_5xx_pct", val,
                                 cfg["error_rate_5xx_pct"], severity_map)

    return breaches

def _check_threshold(breaches, feature, metric, value, threshold, severity_map):
    ratio = value / threshold
    if ratio >= severity_map["critical"]:
        severity = "critical"
    elif ratio >= severity_map["warning"]:
        severity = "warning"
    else:
        return  # within bounds

    breaches.append({
        "feature_id":    feature,
        "metric":        metric,
        "current_value": round(value, 4),
        "threshold":     threshold,
        "breach_delta":  round(value - threshold, 4),
        "ratio":         round(ratio, 4),
        "severity":      severity,
        "timestamp":     datetime.datetime.utcnow().isoformat() + "Z"
    })

# ── Alert Sender ──────────────────────────────────────────────────────────────
def send_alert(breach: dict):
    severity_emoji = "🔴" if breach["severity"] == "critical" else "⚠️"
    payload = {
        "text": (
            f"{severity_emoji} *RuntimeIQ SLA Breach* [{breach['severity'].upper()}]\n"
            f"• Feature: `{breach['feature_id']}`\n"
            f"• Metric: `{breach['metric']}`\n"
            f"• Current: `{breach['current_value']}` | Threshold: `{breach['threshold']}` "
            f"| Delta: `+{breach['breach_delta']}`\n"
            f"• Time: {breach['timestamp']}"
        )
    }
    try:
        resp = requests.post(ALERT_WEBHOOK, json=payload, timeout=10)
        resp.raise_for_status()
        log.info(f"Alert sent for {breach['feature_id']}.{breach['metric']}")
    except Exception as e:
        log.error(f"Alert send failed: {e}")

# ── Breach Log Writer ─────────────────────────────────────────────────────────
def append_breach_log(breaches: list):
    if not breaches:
        return
    log_path = Path(BREACH_LOG_FILE)
    log_path.parent.mkdir(parents=True, exist_ok=True)

    with open(log_path, "a") as f:
        for b in breaches:
            f.write(
                f"\n| {b['timestamp']} | {b['feature_id']} | {b['metric']} "
                f"| {b['current_value']} | {b['threshold']} | {b['breach_delta']:+.4f} "
                f"| **{b['severity']}** |"
            )

# ── Feedback Loop Writer ──────────────────────────────────────────────────────
def write_feedback_loop(breaches: list, thresholds: dict):
    fb_path = Path(FEEDBACK_FILE)
    fb_path.parent.mkdir(parents=True, exist_ok=True)

    # Load existing
    existing = {}
    if fb_path.exists():
        with open(fb_path) as f:
            existing = yaml.safe_load(f) or {}

    overall_severity = "info"
    if any(b["severity"] == "critical" for b in breaches):
        overall_severity = "critical"
    elif any(b["severity"] == "warning" for b in breaches):
        overall_severity = "warning"

    existing["runtime_iq"] = {
        "generated_at": datetime.datetime.utcnow().isoformat() + "Z",
        "summary": (
            f"SLA status across {len(thresholds.get('features', {}))} features. "
            f"{len(breaches)} breach(es) in last cycle."
        ),
        "triggers": breaches,
        "severity": overall_severity
    }

    with open(fb_path, "w") as f:
        yaml.dump(existing, f, default_flow_style=False, sort_keys=False)

# ── Auto-scaling Request ──────────────────────────────────────────────────────
def request_scale_up(thresholds: dict, breaches: list):
    """
    For Kubernetes: patches HPA minReplicas via kubectl or k8s API.
    This sample logs the intent — actual implementation depends on deploy target.
    ControlPlane cost-config.yaml is the hard ceiling.
    """
    critical_breaches = [b for b in breaches if b["severity"] == "critical"]
    if not critical_breaches:
        return

    scaling = thresholds.get("scaling", {})
    max_replicas = scaling.get("max_replicas", 10)
    log.warning(
        f"Scale-up requested due to {len(critical_breaches)} critical breach(es). "
        f"Max allowed replicas: {max_replicas}. "
        f"Implement kubectl patch hpa <name> --patch '{{\"spec\":{{\"minReplicas\": N}}}}'"
    )

# ── Main Loop ─────────────────────────────────────────────────────────────────
def main():
    log.info("RuntimeIQ monitor starting. Poll interval: %ds", POLL_INTERVAL_S)

    # Initialise breach log header if new
    log_path = Path(BREACH_LOG_FILE)
    if not log_path.exists():
        log_path.parent.mkdir(parents=True, exist_ok=True)
        with open(log_path, "w") as f:
            f.write("# SLA Breach Log — Generated by RuntimeIQ\n\n")
            f.write("| Timestamp | Feature | Metric | Value | Threshold | Delta | Severity |\n")
            f.write("|---|---|---|---|---|---|---|\n")

    thresholds = load_thresholds()

    while True:
        log.debug("Starting evaluation cycle")
        breaches = evaluate_sla(thresholds)

        if breaches:
            for breach in breaches:
                log.warning("BREACH: %s.%s = %s (threshold: %s) [%s]",
                            breach["feature_id"], breach["metric"],
                            breach["current_value"], breach["threshold"],
                            breach["severity"])
                send_alert(breach)

            append_breach_log(breaches)
            request_scale_up(thresholds, breaches)
        else:
            log.info("All SLA metrics within thresholds.")

        write_feedback_loop(breaches, thresholds)
        time.sleep(POLL_INTERVAL_S)

if __name__ == "__main__":
    main()
